GOOGLE_API_KEY = "AQ.Ab8RN6L57p6LAkiAg-J47k4ljDOq0CLToAaT6kwx9Fs1w6TvjA"
MONGODB_URI = "mongodb+srv://EE_PC2-CLOUD:erick123@ee-cluster.fpxka90.mongodb.net/?appName=EE-Cluster"
COHERE_API_KEY = "Ho6V11VzpWKORqfw7CEkLUAhz1mhb7Y861DuckHT"
USER = "PC2-Cloud"